package repath

import (
	"maps"
	"regexp"
	"slices"
	"strings"

	"sdmm/internal/aphelion/repath/updatepaths"
)

// variantRule narrows a path decision's rule to one recorded variant. Rule
// filters match a subset of variables, so instances with additional edits
// also match; the exported comment says so.
func variantRule(rule updatepaths.Rule, vars map[string]string) updatepaths.Rule {
	rule.Match.Filters = nil
	if len(vars) == 0 {
		rule.Match.Filters = []updatepaths.Filter{{Kind: updatepaths.FilterNoEdits}}
	}
	for _, name := range slices.Sorted(maps.Keys(vars)) {
		rule.Match.Filters = append(rule.Match.Filters, updatepaths.Filter{Name: name, Value: vars[name]})
	}
	return rule
}

func decisionRule(path string, decision Decision) (updatepaths.Rule, bool) {
	switch {
	case decision.Kind == Delete:
		return DeleteRule(path), true
	case decision.Kind == Apply && decision.Via == ViaRule:
		return decision.Rule, true
	}
	return updatepaths.Rule{}, false
}

func parseVariantKey(key string) map[string]string {
	vars := map[string]string{}
	for _, line := range strings.Split(strings.TrimSuffix(key, "\n"), "\n") {
		if name, value, ok := strings.Cut(line, "="); ok {
			vars[name] = value
		}
	}
	return vars
}

// Rules lists the plan's explicit rules in canonical order: per path, variant
// overrides first, then the path rule. Script and remembered resolutions are
// not rules of this plan and are returned as comments.
func (p Plan) Rules() (rules []updatepaths.Rule, comments []string) {
	paths := slices.Sorted(maps.Keys(p.Paths))
	for path := range p.Variants {
		if _, ok := p.Paths[path]; !ok {
			paths = append(paths, path)
		}
	}
	slices.Sort(paths)
	for _, path := range paths {
		for _, key := range slices.Sorted(maps.Keys(p.Variants[path])) {
			if rule, ok := decisionRule(path, p.Variants[path][key]); ok {
				rules = append(rules, variantRule(rule, parseVariantKey(key)))
			}
		}
		decision, ok := p.Paths[path]
		if !ok {
			continue
		}
		if rule, ok := decisionRule(path, decision); ok {
			rules = append(rules, rule)
		} else if decision.Kind == Apply {
			comments = append(comments, path+" is resolved by "+decision.Summary)
		}
	}
	return rules, comments
}

// ExportScript writes the plan as an UpdatePaths script.
func ExportScript(plan Plan, header string) []byte {
	rules, comments := plan.Rules()
	var b strings.Builder
	b.WriteString("# Generated by AphelionDMM path migration.\n")
	for _, line := range strings.Split(strings.TrimSpace(header), "\n") {
		if line != "" {
			b.WriteString("# " + line + "\n")
		}
	}
	if len(plan.Variants) != 0 {
		b.WriteString("# Variant rules match listed edits; later lines handle the remaining instances.\n")
	}
	for _, comment := range comments {
		b.WriteString("# " + comment + "\n")
	}
	b.Write(updatepaths.Format(rules))
	return []byte(b.String())
}

var scriptName = regexp.MustCompile(`^[0-9]+_[A-Za-z0-9_-]+\.txt$`)

// ValidScriptName follows the tgstation PRNUMBER_NAME.txt convention.
func ValidScriptName(name string) bool { return scriptName.MatchString(name) }
